version: "3.8"

services:
  selenium-grid:
    image: selenium/hub:latest
    container_name: selenium-grid
    ports:
      - "4444:4444"

  chrome-node:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-grid
    environment:
      - SE_EVENT_BUS_HOST=selenium-grid
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2gb

  firefox-node:
    image: selenium/node-firefox:latest
    depends_on:
      - selenium-grid
    environment:
      - SE_EVENT_BUS_HOST=selenium-grid
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2gb

  tests:
    image: gradle:latest
    container_name: gradle-tests
    depends_on:
      - chrome-node
      - firefox-node
    volumes:
      - .:/home/gradle/project
    working_dir: /home/gradle/project
    command: gradle test --info